# Generated by Django 5.1 on 2026-05-19 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], max_length=5)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('prompt', models.TextField()),
                ('min_words', models.PositiveSmallIntegerField(default=250)),
                ('time_minutes', models.PositiveSmallIntegerField(default=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='writing/task_images/')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WritingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=10)),
                ('content', models.TextField()),
                ('word_count', models.PositiveSmallIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band_task_response', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('band_coherence', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('band_lexical', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('band_grammar', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('corrected_text', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writing_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.writingtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='writingtask',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='writing.writingtest'),
        ),
    ]
