# Generated by Django 6.0.5 on 2026-05-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('tfng', 'True / False / Not Given'), ('fill', 'Fill in the Blank'), ('table', 'Table Completion'), ('note', 'Note Completion'), ('summary', 'Summary Completion'), ('match', 'Matching Headings'), ('short', 'Short Answer')], max_length=10),
        ),
    ]
