# Generated by Django 6.0.5 on 2026-07-16 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_add_question_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongroup',
            name='passage',
        ),
        migrations.AlterModelOptions(
            name='readingattempt',
            options={},
        ),
        migrations.RemoveField(
            model_name='readingattempt',
            name='time_taken_seconds',
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='answer_key',
            field=models.JSONField(default=dict, help_text="JSON mapping of question numbers to correct answers e.g. {'1': 'A', '2': 'TRUE'}"),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='questions_html',
            field=models.TextField(blank=True, help_text='Raw HTML for the questions section'),
        ),
        migrations.AlterField(
            model_name='readingattempt',
            name='score_raw',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='readingattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readingpassage',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionGroup',
        ),
    ]
