# Generated by Django 5.1 on 2026-05-19 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('part1', 'Part 1'), ('part2', 'Part 2'), ('part3', 'Part 3')], max_length=5)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('prompt', models.TextField()),
                ('prep_time_seconds', models.PositiveSmallIntegerField(default=60)),
                ('speak_time_seconds', models.PositiveSmallIntegerField(default=120)),
                ('cue_card_points', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='speaking/recordings/')),
                ('duration_seconds', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(default='submitted', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('band_fluency', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('band_lexical', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('band_grammar', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('band_pronunciation', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speaking.speakingpart')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaking_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='speakingpart',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='speaking.speakingtest'),
        ),
    ]
