# Generated by Django 5.1 on 2026-05-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtest',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='listening/audio/'),
        ),
    ]
