# Generated by Django 5.1 on 2026-05-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0002_listeningtest_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningsection',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='listening/audio/'),
        ),
    ]
