# Generated by Django 6.0.5 on 2026-05-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0003_listening_section_audio_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_type',
            field=models.CharField(choices=[('fill', 'Form / Sentence Completion'), ('table', 'Table Completion'), ('note', 'Note Completion'), ('mcq', 'Multiple Choice'), ('match', 'Matching')], default='fill', max_length=20),
        ),
    ]
