# Generated by Django 6.0.5 on 2026-05-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0004_add_question_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningsection',
            name='audio_file',
        ),
    ]
