# Generated by Django 6.0.5 on 2026-06-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0005_remove_listeningsection_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningsection',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='listening/sections/'),
        ),
    ]
