# Generated by Django 6.0.5 on 2026-07-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0007_alter_listeningattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningsection',
            name='answer_key',
            field=models.JSONField(default=dict, help_text="JSON mapping of question numbers to correct answers e.g. {'1': 'A', '2': 'apple'}"),
        ),
        migrations.AddField(
            model_name='listeningsection',
            name='questions_html',
            field=models.TextField(blank=True, help_text='Raw HTML for the questions section'),
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Direct link to audio, or Google Drive link', max_length=500, null=True),
        ),
    ]
